/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 *
 * NOTE: `payload generate:types` currently fails to run in this environment
 * (Node 24 + a loadEnv/@next-env interop bug inside Payload's own CLI, confirmed
 * unrelated to our config — reproduced across three different invocation paths).
 * The six collection types below (Player, Venue, Article, Championship,
 * LeaderboardEntry, TeeTimeRound) were added by hand to unblock tsc/build.
 * Re-run the real generator once this is deployed (Vercel's Linux build may not
 * hit the same bug) or once the upstream issue is fixed, and remove this note.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    players: Player;
    venues: Venue;
    articles: Article;
    championships: Championship;
    'leaderboard-entries': LeaderboardEntry;
    'tee-time-rounds': TeeTimeRound;
    'player-statistics': PlayerStatistic;
    'legal-pages': LegalPage;
    scorecards: Scorecard;
    'live-blog-posts': LiveBlogPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'homepage-settings': HomepageSettingsGlobal;
    'site-theme': SiteThemeGlobal;
    'sponsor-clock': SponsorClockGlobal;
    'tournament-status': TournamentStatusGlobal;
    'page-banners': PageBannersGlobal;
    'sponsors': SponsorsGlobal;
    'social-links': SocialLinksGlobal;
    'contact-page': ContactPageSettingsGlobal;
    'media-page': MediaPageSettingsGlobal;
    'careers-page': CareersPageSettingsGlobal;
  };
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface Player {
  id: string;
  name: string;
  slug?: string | null;
  country: string;
  countryCode: string;
  dateOfBirth?: string | null;
  age?: number | null;
  championshipHandicap?: number | null;
  previousOpens: number;
  inField?: boolean | null;
  cdhNumber?: string | null;
  photo?: (string | Media) | null;
  bio?: unknown;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface Venue {
  id: string;
  name: string;
  slug?: string | null;
  location: string;
  region: string;
  countryCode?: string | null;
  country?: string | null;
  parYardage?: string | null;
  timesHosted: number;
  firstHosted: number;
  lastHosted: number;
  description: string;
  overview?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  imageLabel: string;
  image?: (string | Media) | null;
  courseRating?: number | null;
  slopeRating?: number | null;
  holes?:
    | {
        holeNumber: number;
        par: number;
        yards: number;
        si: number;
        id?: string | null;
      }[]
    | null;
  outPar?: number | null;
  outYards?: number | null;
  inPar?: number | null;
  inYards?: number | null;
  totalPar?: number | null;
  totalYards?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface Article {
  id: string;
  title: string;
  slug?: string | null;
  dek: string;
  category: 'Championship News' | 'Player Features' | 'History' | 'Tickets' | 'Course Guide';
  publishedAt: string;
  readTimeMinutes: number;
  heroLabel: string;
  image?: (string | Media) | null;
  body: unknown;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface Championship {
  id: string;
  year: number;
  isActive?: boolean | null;
  date?: string | null;
  venue: string | Venue;
  winnerName?: string | null;
  winnerCountry?: string | null;
  winnerPlayer?: (string | Player) | null;
  scoreToPar?: number | null;
  margin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface InfoCardGroupBlock {
  eyebrow?: string | null;
  heading: string;
  cards: {
    image?: (string | Media) | null;
    tone?: ('navy' | 'gold' | 'dusk' | 'slate') | null;
    title: string;
    description?: string | null;
    linkLabel?: string | null;
    linkHref: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoCardGroup';
}
export interface CtaBannerBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  buttonLabel: string;
  buttonHref: string;
  tone?: ('light' | 'dark' | 'gold') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
export interface RichTextBlock {
  heading?: string | null;
  content: unknown;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
export interface HomepageSettingsGlobal {
  id: string;
  currentChampion: {
    championship: string | Championship;
    article: string | Article;
  };
  sections?: (InfoCardGroupBlock | CtaBannerBlock | RichTextBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface SiteThemeGlobal {
  id: string;
  colors: {
    primaryColor: string;
    accentColor: string;
  };
  branding: {
    logo?: (string | Media) | null;
    favicon?: (string | Media) | null;
    championBadge?: (string | Media) | null;
  };
  fontPreset: 'fraunces-inter' | 'playfair-source-sans' | 'newsreader-manrope';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface SponsorClockGlobal {
  id: string;
  sponsor: {
    name: string;
    tagline: string;
    logo?: (string | Media) | null;
    faceColor: string;
  };
  graphics: {
    faceImage?: (string | Media) | null;
    faceImageRetina?: (string | Media) | null;
    hourHand?: (string | Media) | null;
    minuteHand?: (string | Media) | null;
    secondHand?: (string | Media) | null;
    centerCap?: (string | Media) | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface TournamentStatusGlobal {
  id: string;
  competitionComplete?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface PageBannersGlobal {
  id: string;
  leaderboard?: (string | Media) | null;
  leaderboardEyebrow?: string | null;
  leaderboardTitle?: string | null;
  leaderboardDescription?: string | null;
  teeTimes?: (string | Media) | null;
  teeTimesEyebrow?: string | null;
  teeTimesTitle?: string | null;
  teeTimesDescription?: string | null;
  venues?: (string | Media) | null;
  venuesEyebrow?: string | null;
  venuesTitle?: string | null;
  venuesDescription?: string | null;
  field?: (string | Media) | null;
  fieldEyebrow?: string | null;
  fieldTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface SponsorsGlobal {
  id: string;
  pageEyebrow?: string | null;
  pageTitle: string;
  pageDescription: string;
  patrons?:
    | {
        name: string;
        logo: string | Media;
        websiteUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  officialSuppliers?:
    | {
        name: string;
        logo: string | Media;
        websiteUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface SocialLinksGlobal {
  id: string;
  links?:
    | {
        platform: 'Facebook' | 'Instagram' | 'LinkedIn' | 'X' | 'YouTube' | 'TikTok' | 'Other';
        label?: string | null;
        icon?: string | Media | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface ContactPageSettingsGlobal {
  id: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface MediaPageSettingsGlobal {
  id: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription: string;
  resourcesEyebrow?: string | null;
  resourcesTitle: string;
  resources?:
    | {
        icon: 'Trophy' | 'Compass' | 'HeartHandshake' | 'FileText' | 'Image' | 'Mail' | 'Shield' | 'Star' | 'Users' | 'Megaphone';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaDescription: string;
  ctaButtonLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface CareersPageSettingsGlobal {
  id: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription: string;
  valuesEyebrow?: string | null;
  valuesTitle: string;
  values?:
    | {
        icon: 'Trophy' | 'Compass' | 'HeartHandshake' | 'FileText' | 'Image' | 'Mail' | 'Shield' | 'Star' | 'Users' | 'Megaphone';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  rolesEyebrow?: string | null;
  rolesTitle: string;
  openRoles?:
    | {
        title: string;
        location: string;
        type: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaDescription: string;
  ctaButtonLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hand-added — see note at top of file.
 */
export interface LeaderboardEntry {
  id: string;
  round: 'round2' | 'round4';
  position: number;
  tied?: boolean | null;
  player: string | Player;
  scoreToPar: number;
  thru: string;
  rounds?:
    | {
        score: number;
        id?: string | null;
      }[]
    | null;
  total: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface TeeTimeRound {
  id: string;
  round: 'Practice' | 'Championship';
  championship?: (string | Championship) | null;
  date: string;
  archived?: boolean | null;
  groups?:
    | {
        time: string;
        tee: '1st' | '10th';
        players: (string | Player)[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface PlayerStatistic {
  id: string;
  player: string | Player;
  drivingDistanceYards: number;
  greensInRegulationHit: number;
  totalPutts: number;
  par5ScoringToPar: number;
  scramblingPercent: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface LegalPage {
  id: string;
  title: string;
  slug: string;
  body: unknown;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface Scorecard {
  id: string;
  player: string | Player;
  championship: string | Championship;
  teeTime?: string | null;
  scoreUpdatedAt?: string | null;
  holes?:
    | {
        holeNumber: number;
        strokes?: number | null;
        id?: string | null;
      }[]
    | null;
  holesCompleted?: number | null;
  grossTotal?: number | null;
  nettTotal?: number | null;
  stablefordTotal?: number | null;
  toParGross?: number | null;
  toParNett?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hand-added — see note at top of file.
 */
export interface LiveBlogPost {
  id: string;
  category:
    | "eagle"
    | "birdie"
    | "bogey"
    | "moving-up"
    | "charge"
    | "moving-down"
    | "trouble"
    | "leader"
    | "through"
    | "clubhouse-leader"
    | "round-complete"
    | "last-group"
    | "championship";
  headline: string;
  body: string;
  competition?: ("main" | "stableford" | "scratch") | null;
  championship: string | Championship;
  player?: (string | Player) | null;
  holeNumber?: number | null;
  scoreRelative?: number | null;
  postedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}